### ISSUE TITLE
Question about firebase

### ISSUE THREAD

**Issue by irx0** [manuelernesto/Takeaway_Kotlin#2]
Hello,
I was trying to implement my own firebase database for this project for learning and I was wondering how is the realtime database structured? I managed to add category section easily by following the code but everything else I haven't able to figure out.
/edit I figured it out, the menuId had to be the name of the Category child :)

**Comment by manuelernesto** [comment]
Hi, @irx0, 

Sorry for the delay, hope its help: 

- Category (image and name) 

- Product (description, discount, image, menuId, name, and price )

- User (name, password, and phone)

- Request (List of Product: Foods, Address, total, and user detail )
